CREATE TABLE B_SUBFILE
(
	SUBFILE_ID			SERIAL PRIMARY KEY,
	SUBFILE_SUB_ID		INTEGER,
	SUBFILE_FILE_ID		INTEGER,
	
	CONSTRAINT B_SUBFILE_FILE_ID_FK FOREIGN KEY (SUBFILE_FILE_ID)
	REFERENCES A_FILE (FILE_ID) ON DELETE CASCADE,
	CONSTRAINT B_SUBFILE_SUB_ID_FK FOREIGN KEY (SUBFILE_SUB_ID)
	REFERENCES B_SUBS (SUB_ID) ON DELETE CASCADE
);