CREATE TABLE B_USER 
(
	USER_ID 			SERIAL PRIMARY KEY, 
	USER_LEVEL_ID 		INTEGER NOT NULL, 
	TIME_STAMP_CREATED 	TIMESTAMP(6) NOT NULL, 
	TIME_STAMP_LASTLOG 	TIMESTAMP(6) NOT NULL, 
	USER_NAME 			VARCHAR(50) NOT NULL, 
	EMAIL 				VARCHAR(50) NOT NULL, 
	PASSWORD 			VARCHAR(128) NOT NULL, 
	NAME 				VARCHAR(50) NOT NULL, 
	SURNAME 			VARCHAR(50) NOT NULL, 
	ACTIVE 				INTEGER NOT NULL, 
	CONSTRAINT B_USER_LEVEL_FK FOREIGN KEY (USER_LEVEL_ID)
	REFERENCES A_USER_LEVEL (USER_LEVEL_ID) ON DELETE CASCADE
);

CREATE INDEX B_USER_LEVEL_FK_I ON B_USER (USER_LEVEL_ID);
