CREATE TABLE C_PROCESS
(	
	P_ID 				SERIAL PRIMARY KEY, 
	P_TYPE_ID		 	INTEGER,
    P_NAME				VARCHAR(200),
	P_FILE_ID			INTEGER,
	P_DATE				TIMESTAMP(6)--,

	--CONSTRAINT C_PROCESS_FILE_ID_FK FOREIGN KEY (P_FILE_ID)
	--REFERENCES A_FILE (FILE_ID)
);

CREATE INDEX C_PROCESS_P_FILE_ID_I ON C_PROCESS (P_FILE_ID);

