CREATE TABLE R_PERMISSIONS
(	
	ROW_ID 					SERIAL PRIMARY KEY, 
	FILE_ID			 		INTEGER, 
	PERMISSION_ID			INTEGER, 
	PERMISSION				VARCHAR(200)
);

CREATE INDEX R_PERMISSIONS_FILE_ID_I ON R_PERMISSIONS (FILE_ID);
